In [1]:
import numpy as np

In [2]:
# Задание 1
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
# Задание 2
a1 = a.reshape(2,6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a2 = a.reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a3 = a.reshape(4,3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a4 = a.reshape(6,2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a5 = a.reshape(12,1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [8]:
# Задание 3
a6 = a.reshape(2, -1)
a6

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a7 = a.reshape(3, -1)
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a8 = a.reshape(12, -1)
a8

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [11]:
a9 = a.reshape(-1, 3)
a9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a10 = a.reshape(-1, 2)
a10

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
# Задание 4
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# Ответ: Нет
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [14]:
a5.ndim

2

In [15]:
# Задание 5
a11 = np.random.randn(3, 4)
a11

array([[-1.26690983, -0.80834346,  0.58351347,  0.9160002 ],
       [ 0.25403643,  0.78598826, -0.08327324, -0.97578661],
       [-0.9257785 ,  1.81914665,  1.31698884,  1.26952506]])

In [16]:
a12 = a11.flatten()
a12

array([-1.26690983, -0.80834346,  0.58351347,  0.9160002 ,  0.25403643,
        0.78598826, -0.08327324, -0.97578661, -0.9257785 ,  1.81914665,
        1.31698884,  1.26952506])

In [17]:
a11.size == a12.size

True

In [18]:
# Задание 6
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [19]:
# Задание 7
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [20]:
np.array_equal(a, b)

True

In [21]:
# Задание 8
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [22]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
c = np.vstack((a, b)) 
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
c.size

10

In [25]:
# Задание 9
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [28]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [29]:
B.size

16

In [30]:
# Определитель матрицы B = 0, поэтому для неё невозможно вычислить обратную матрицу
np.linalg.det(B)

0.0

In [31]:
# Задание 10
np.random.seed(42)

In [32]:
# Задание 11
c = np.arange(0, 16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
# Задание 12
np.sqrt(c.size)

4.0

In [34]:
C = c.reshape(4, 4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
D = 10 * C + B
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [36]:
np.linalg.det(D)

5.18953807259442e-26

In [37]:
np.linalg.matrix_rank(D)

2

In [38]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

In [39]:
# Задание 13
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [40]:
E = np.where(D_inv, B, C)
E

array([[  5,   1,   2,  32],
       [ 14,   5,  86,   7],
       [  8,  86,  10,  11],
       [ 32,  13, 212, 302]])